name: Generate Skins Index

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Skins/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Skins/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Generate index.json
        run: python generate_index.py
          
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update index.json" && git push)
